name: Build and Test PostgreSQL ${{ matrix.version }}

on:
  pull_request:
    branches: [main, master]
  push:
    branches: [main, master]
jobs:
  build-ubuntu:
    name: Build on PostgreSQL ${{ matrix.version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [13, 14]
    container:
      image: postgres:${{ matrix.version }}
    steps:
    - name: Install dependencies
      env:
        DEBIAN_FRONTEND: noninteractiv
      run: |
        apt-get update
        apt-get install -qy make gcc postgresql-server-dev-${{ matrix.version }} postgresql-client-${{ matrix.version }}
    - uses: actions/checkout@v2
    - name: Build extensions
      run: make
    - name: Install extensions
      run: make install
    - name: Start PostgreSQL server
      env:
        POSTGRES_HOST_AUTH_METHOD: trust
      run: gosu postgres docker-entrypoint.sh postgres >/var/log/postgresql/postgresql.log 2>&1 &
    - name: Wait for server to start
      env:
        PGUSER: postgres
      run: sleep 10 && pg_isready -t20
    - name: Run tests
      env:
        PGUSER: postgres
      run: make installcheck
    - name: Show regressdiff
      if: ${{ failure() }}
      run: test -r regression.diffs && cat regression.diffs
    - name: Archive production artifacts
      if: ${{ always() }}
      uses: actions/upload-artifact@v3
      with:
        name: postgresql-${{ matrix.version}}-${{ matrix.release }}-log
        path: /var/log/postgresql
